env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "CirrusCI"
    CIRRUS_WORKING_DIR: "/tmp/ci"
    TOKEN: "ENCRYPTED[!fe92b05186850ad5deb3f6b17c377c157b7f4eb2b23b5c51f27f9779ac4e6acc537b41972fb3b3ce97b8b640eb414a55!]"
    VERSIONS: "Dev-1"
    INFORELEASE: "X-UI Vietnamese Language\n\nNgưng support 32Bit\nThêm Bot Telegram và CloudFlare\nChấp nhận clear dung lượng đã dùng\nThông báo dung lượng qua Telegram\n\nSupport: amd64, arm64v8a, s390x.\n\n*** Vui lòng tạo Issues nếu có bất kỳ lỗi nào"
    DEBIAN_FRONTEND: "noninteractive"
    SSHKEY1: "ENCRYPTED[!e6706dd32621e320165c4cbc6a710c42329ed1149221addf97dd393018e52bf72b2b9b3cdae7cc1aba7863d394a53f46!]"
    SSHKEY2: "ENCRYPTED[!a5d564aa645ea61bb70aa6ce21a8f8bb51766a8b9fc80dec8aebcf34df41a0afd66f6e7766acea683fece365311949e8!]"
    USERNAME: "ENCRYPTED[!84300cf406cc0695b827f4cbc9883c7712ab134798e1347bccac9395580fd618298d6dd1ff7897e77eea3a3203fda42b!]"
    EMAIL: "ENCRYPTED[!a03cbd7c4b2f675b5535c1199bc8bd6eb2f30db7812c7846e372b3e51d00d3c1b4de9e7654bf683c1e5728aba6bfba0e!]"

task:
  name: Compile X-UI
  only_if: $CIRRUS_REPO_OWNER == 'dopaemon' && $CIRRUS_BRANCH == 'master'
  skip: $CIRRUS_BRANCH != 'master'
  container:
    image: dopaemon/bionic:latest
    cpu: 4
    memory: 8G
  install_packages_script:
    - sudo rm -rf /tmp/ci/*
    - sudo apt update
    - sudo apt install software-properties-common jq wget unzip rclone aria2 git gcc-riscv64-linux-gnu gcc-7-aarch64-linux-gnu gcc-7-s390x-linux-gnu gcc-aarch64-linux-gnu gcc-s390x-linux-gnu -y -q
    - sudo /usr/bin/apt-key adv --no-tty --keyserver hkp://keyserver.ubuntu.com:80 --recv C99B11DEB97541F0
    - sudo apt-add-repository https://cli.github.com/packages
    - sudo apt-get update
    - sudo apt-get install gh
    - sudo apt remove golang-go gccgo-go -y
    - curl -OL https://go.dev/dl/go1.18.3.linux-amd64.tar.gz
    - sha256sum go1.18.3.linux-amd64.tar.gz
    - sudo tar -C /usr/local -xvf go1.18.3.linux-amd64.tar.gz
    - touch ~/.goi
    - echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.goi
    - source ~/.goi
  sshkey_script:
    - mkdir -p ~/.ssh
    - sudo chmod 700 ~/.ssh/
    - sudo rm -rf /root/.ssh
    - git config --global --add safe.directory /tmp/ci/x-ui/src-zip/x-ui
    - git config --global user.name "$USERNAME"
    - git config --global user.email "$EMAIL"
    - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    - touch ~/.ssh/id_ed25519.pub
    - touch ~/.ssh/id_ed25519
    - echo "$SSHKEY1" > ~/.ssh/id_ed25519.pub
    - echo "$SSHKEY2" > ~/.ssh/id_ed25519
    - sudo chmod 400 ~/.ssh/*
    - ssh-keygen -R $(curl ifconfig.me)
  source_script:
    - source ~/.goi
    - sudo mkdir -p /tmp/ci/x-ui/
    - sudo mkdir -p /tmp/ci/platform/
    - sudo chmod 777 /tmp/ci/x-ui/
    - sudo chmod 777 /tmp/ci/platform/
    - git clone -b master --single-branch --depth="1" https://github.com/dopaemon/x-ui.git /tmp/ci/x-ui/src
    - echo "$VERSIONS By https://github.com/dopaemon" > /tmp/ci/x-ui/src/config/version
  env-targz_script:
    - sudo mkdir -p /tmp/ci/x-ui/src-zip/x-ui/bin
    - sudo chmod 777 /tmp/ci/x-ui/src-zip/x-ui/bin
    - sudo chmod 777 /tmp/ci/x-ui/src-zip/x-ui
    - sudo chmod 777 /tmp/ci/x-ui/src-zip
    - cp -rv /tmp/ci/x-ui/src/x-ui.service /tmp/ci/x-ui/src-zip/x-ui/
    - cp -rv /tmp/ci/x-ui/src/x-ui.sh /tmp/ci/x-ui/src-zip/x-ui/
    - wget -O /tmp/ci/x-ui/src-zip/x-ui/bin/geoip.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
    - wget -O /tmp/ci/x-ui/src-zip/x-ui/bin/geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
  xray_source_script:
    - sudo mkdir -p /tmp/ci/XrayPrebuilt
    - sudo chmod 777 /tmp/ci/XrayPrebuilt
    - git clone -b main --single-branch https://github.com/XTLS/Xray-core.git /tmp/ci/XrayPrebuilt/Xray-core 
    - cd /tmp/ci/XrayPrebuilt/
    - git clone https://github.com/SagerNet/sing-shadowsocks.git
  xray_build_arm64_script:
    - source ~/.goi
    - cd /tmp/ci/XrayPrebuilt/Xray-core
    - CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc  go build -o OUT/xray-arm64 -v -trimpath -ldflags "-s -w -buildid=" ./main
  arm64_script:
    - source ~/.goi
    - cd /tmp/ci/x-ui/src
    - CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc go build -ldflags='-extldflags=-static' -tags sqlite_omit_load_extension -o xui-arm64 -v main.go
    - mv xui-arm64 /tmp/ci/platform/
  branch_arm64_script:
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/.git
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/x-ui
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/bin/xray-linux-*
    - mv /tmp/ci/platform/xui-arm64 /tmp/ci/x-ui/src-zip/x-ui/x-ui
    - mv /tmp/ci/XrayPrebuilt/Xray-core/OUT/xray-arm64 /tmp/ci/x-ui/src-zip/x-ui/bin/xray-linux-arm64
    - cd /tmp/ci/x-ui/src-zip/x-ui
    - git init && git add -vA && git commit -sm "Release: X-UI $VERSIONS ARM64" && git remote add origin git@github.com:dopaemon/x-ui.git
    - git checkout -b "X-UI-Dev-ARM64"
    - echo "yes" | git push -uf origin "X-UI-Dev-ARM64"
  github_script:
    - sudo rm -rf /tmp/ci/*
    - sudo chmod 777 /tmp/ci
    - mkdir -p /tmp/ci/arm64
    - git clone -b "X-UI-Dev-ARM64" --single-branch https://github.com/dopaemon/x-ui.git /tmp/ci/arm64/x-ui
    - cd /tmp/ci/arm64/
    - rm -rvf x-ui/.git
    - tar -czvf x-ui-linux-arm64.tar.gz x-ui
  release_script:
    - cd /tmp/ci
    - git clone -b master --single-branch https://github.com/dopaemon/x-ui.git
    - mkdir -p /tmp/ci/out/
    - mv /tmp/ci/arm64/x-ui-linux-arm64.tar.gz /tmp/ci/out/
    - gh config set git_protocol ssh --host github.com
    - touch mytoken.txt
    - echo "$TOKEN" > mytoken.txt
    - gh auth login --with-token < mytoken.txt
    - bash <(curl -Ls https://raw.githubusercontent.com/dopaemon/x-ui/master/release.sh)
    - echo "yes" | gh release create $VERSIONS /tmp/ci/out/*.tar.gz --notes "$INFORELEASE" --title "X-UI $VERSIONS - Weekly - $(date +"%d-%m-%Y")"
