env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "CirrusCI"
    CIRRUS_WORKING_DIR: "/tmp/ci"
    TOKEN: "ENCRYPTED[!fe92b05186850ad5deb3f6b17c377c157b7f4eb2b23b5c51f27f9779ac4e6acc537b41972fb3b3ce97b8b640eb414a55!]"
    VERSIONS: "0.3.4.8-Sofbox"
    INFORELEASE: "X-UI Vietnamese Language\n\nThêm Bot Telegram và CloudFlare\nChấp nhận clear dung lượng đã dùng\nThông báo dung lượng qua Telegram\n\nSupport: 386, amd64, [arm32v5 v6 v7], arm64, mips, mips64, riscv64, s390x.\nOS: CentOS, Ubuntu, Debian, Armbian\n\n*** Vui lòng tạo Issues nếu có bất kỳ lỗi nào"
    DEBIAN_FRONTEND: "noninteractive"
    SSHKEY1: "ENCRYPTED[!e6706dd32621e320165c4cbc6a710c42329ed1149221addf97dd393018e52bf72b2b9b3cdae7cc1aba7863d394a53f46!]"
    SSHKEY2: "ENCRYPTED[!a5d564aa645ea61bb70aa6ce21a8f8bb51766a8b9fc80dec8aebcf34df41a0afd66f6e7766acea683fece365311949e8!]"
    USERNAME: "ENCRYPTED[!84300cf406cc0695b827f4cbc9883c7712ab134798e1347bccac9395580fd618298d6dd1ff7897e77eea3a3203fda42b!]"
    EMAIL: "ENCRYPTED[!a03cbd7c4b2f675b5535c1199bc8bd6eb2f30db7812c7846e372b3e51d00d3c1b4de9e7654bf683c1e5728aba6bfba0e!]"
    NGORKTOKEN: "ENCRYPTED[bb6140df5f51e60475ee168d793d74a1cf48f0ccc3c735d0604326b69f49166e9a3f1bd4b1dfee7851d81279a0fcadea]"

task:
  name: Compile X-UI
  only_if: $CIRRUS_REPO_OWNER == 'dopaemon' && $CIRRUS_BRANCH == 'main'
  skip: $CIRRUS_BRANCH != 'main'
  container:
    image: dopaemon/bionic:latest
    cpu: 8
    memory: 16G

  sshkey_script:
    - mkdir -p ~/.ssh
    - sudo chmod 700 ~/.ssh/
    - sudo rm -rf /root/.ssh
    - git config --global --add safe.directory /tmp/ci/x-ui/src-zip/x-ui
    - git config --global user.name "$USERNAME"
    - git config --global user.email "$EMAIL"
    - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    - touch ~/.ssh/id_ed25519.pub
    - touch ~/.ssh/id_ed25519
    - echo "$SSHKEY1" > ~/.ssh/id_ed25519.pub
    - echo "$SSHKEY2" > ~/.ssh/id_ed25519
    - sudo chmod 400 ~/.ssh/*
    - ssh-keygen -R $(curl ifconfig.me)

  install_script:
    - curl -OL https://golang.org/dl/go1.18.1.linux-amd64.tar.gz
    - sudo tar -C /usr/local -xvf go1.18.1.linux-amd64.tar.gz

  source_script:
    - sudo mkdir -p /tmp/ci/x-ui/
    - sudo chmod 777 /tmp/ci/x-ui/
    - git clone -b main --single-branch --depth="1" https://github.com/dopaemon/x-ui.git /tmp/ci/x-ui/src
    - echo "$VERSIONS By https://github.com/dopaemon" > /tmp/ci/x-ui/src/config/version

  compile_x-ui_script:
    - export PATH=$PATH:/usr/local/go/bin
    - cd /tmp/ci/x-ui/src && mkdir -p OUT
    - compile-xui

  compile_XrayR_script:
    - export PATH=$PATH:/usr/local/go/bin
    - sudo mkdir -p /tmp/ci/Xray-Core
    - sudo chmod 777 /tmp/ci/Xray-Core
    - git clone -b main --single-branch --depth="1" https://github.com/XTLS/Xray-core.git /tmp/ci/Xray-Core/src
    - cd /tmp/ci/Xray-Core/src && mkdir -p OUT
    - compile-xray-core

  check_OUT_script:
    - echo "X-UI" > /dev/null
    - ls /tmp/ci/x-ui/src/OUT
    - sudo chmod +x /tmp/ci/x-ui/src/OUT/*
    - echo "Xray Core" > /dev/null
    - ls /tmp/ci/Xray-Core/src/OUT
    - sudo chmod +x /tmp/ci/Xray-Core/src/OUT/*

  create_directory_script:
    - sudo mkdir -p /tmp/work
    - sudo chmod 777 /tmp/work
    - mkdir -p /tmp/work/OUT
    - cd /tmp/work
    - mkdir -pv 386/x-ui amd64/x-ui arm32v5/x-ui arm32v6/x-ui arm32v7/x-ui arm64/x-ui mips/x-ui mips64/x-ui mips64le/x-ui mipsle/x-ui riscv64/x-ui s390x/x-ui

  geoip_script:
    - cd /tmp/work
    - mkdir -p geoip
    - wget -O geoip/geoip.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
    - wget -O geoip/geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
    - sudo chmod +x /tmp/work/geoip/*

  compress_script:
    # Tree Map
    #
    # x-ui/
    #  ├── x-ui.service
    #  ├── x-ui.sh
    #  ├── x-ui
    #  └── bin/
    #       ├── geoip.dat
    #       ├── geosite.dat
    #       └── xray-linux-$ARCH

    # arch: 386
    - cd /tmp/work/386/x-ui
    - mkdir -p bin
    - cp -r /tmp/ci/x-ui/src/x-ui.service ./
    - cp -r /tmp/ci/x-ui/src/x-ui.sh ./
    - cp -r /tmp/work/geoip/geoip.dat bin/
    - cp -r /tmp/work/geoip/geosite.dat bin/
    - mv /tmp/ci/x-ui/src/OUT/X-UI-linux-386 x-ui
    - mv /tmp/ci/Xray-Core/src/OUT/Xray-Core-linux-386 bin/xray-linux-386
    - cd ../
    - tar -czf x-ui-linux-386.tar.gz x-ui
    - mv x-ui-linux-386.tar.gz /tmp/work/OUT/

    # arch: amd64
    - cd /tmp/work/amd64/x-ui
    - mkdir -p bin
    - cp -r /tmp/ci/x-ui/src/x-ui.service ./
    - cp -r /tmp/ci/x-ui/src/x-ui.sh ./
    - cp -r /tmp/work/geoip/geoip.dat bin/
    - cp -r /tmp/work/geoip/geosite.dat bin/
    - mv /tmp/ci/x-ui/src/OUT/X-UI-linux-amd64 x-ui
    - mv /tmp/ci/Xray-Core/src/OUT/Xray-Core-linux-amd64 bin/xray-linux-amd64
    - cd ../
    - tar -czf x-ui-linux-amd64.tar.gz x-ui
    - mv x-ui-linux-amd64.tar.gz /tmp/work/OUT/

    # arch: arm32v5
    - cd /tmp/work/arm32v5/x-ui
    - mkdir -p bin
    - cp -r /tmp/ci/x-ui/src/x-ui.service ./
    - cp -r /tmp/ci/x-ui/src/x-ui.sh ./
    - cp -r /tmp/work/geoip/geoip.dat bin/
    - cp -r /tmp/work/geoip/geosite.dat bin/
    - mv /tmp/ci/x-ui/src/OUT/X-UI-linux-arm32v5 x-ui
    - mv /tmp/ci/Xray-Core/src/OUT/Xray-Core-linux-arm32v5 bin/xray-linux-arm32v5
    - cd ../
    - tar -czf x-ui-linux-arm32v5.tar.gz x-ui
    - mv x-ui-linux-arm32v5.tar.gz /tmp/work/OUT/

    # arch: arm32v6
    - cd /tmp/work/arm32v6/x-ui
    - mkdir -p bin
    - cp -r /tmp/ci/x-ui/src/x-ui.service ./
    - cp -r /tmp/ci/x-ui/src/x-ui.sh ./
    - cp -r /tmp/work/geoip/geoip.dat bin/
    - cp -r /tmp/work/geoip/geosite.dat bin/
    - mv /tmp/ci/x-ui/src/OUT/X-UI-linux-arm32v6 x-ui
    - mv /tmp/ci/Xray-Core/src/OUT/Xray-Core-linux-arm32v6 bin/xray-linux-arm32v6
    - cd ../
    - tar -czf x-ui-linux-arm32v6.tar.gz x-ui
    - mv x-ui-linux-arm32v6.tar.gz /tmp/work/OUT/

    # arch: arm32v7
    - cd /tmp/work/arm32v7/x-ui
    - mkdir -p bin
    - cp -r /tmp/ci/x-ui/src/x-ui.service ./
    - cp -r /tmp/ci/x-ui/src/x-ui.sh ./
    - cp -r /tmp/work/geoip/geoip.dat bin/
    - cp -r /tmp/work/geoip/geosite.dat bin/
    - mv /tmp/ci/x-ui/src/OUT/X-UI-linux-arm32v7 x-ui
    - mv /tmp/ci/Xray-Core/src/OUT/Xray-Core-linux-arm32v7 bin/xray-linux-arm32v7
    - cd ../
    - tar -czf x-ui-linux-arm32v7.tar.gz x-ui
    - mv x-ui-linux-arm32v7.tar.gz /tmp/work/OUT/

    # arch: arm64
    - cd /tmp/work/arm64/x-ui
    - mkdir -p bin
    - cp -r /tmp/ci/x-ui/src/x-ui.service ./
    - cp -r /tmp/ci/x-ui/src/x-ui.sh ./
    - cp -r /tmp/work/geoip/geoip.dat bin/
    - cp -r /tmp/work/geoip/geosite.dat bin/
    - mv /tmp/ci/x-ui/src/OUT/X-UI-linux-arm64 x-ui
    - mv /tmp/ci/Xray-Core/src/OUT/Xray-Core-linux-arm64 bin/xray-linux-arm64
    - cd ../
    - tar -czf x-ui-linux-arm64.tar.gz x-ui
    - mv x-ui-linux-arm64.tar.gz /tmp/work/OUT/

    # arch: mips
    - cd /tmp/work/mips/x-ui
    - mkdir -p bin
    - cp -r /tmp/ci/x-ui/src/x-ui.service ./
    - cp -r /tmp/ci/x-ui/src/x-ui.sh ./
    - cp -r /tmp/work/geoip/geoip.dat bin/
    - cp -r /tmp/work/geoip/geosite.dat bin/
    - mv /tmp/ci/x-ui/src/OUT/X-UI-linux-mips x-ui
    - mv /tmp/ci/Xray-Core/src/OUT/Xray-Core-linux-mips bin/xray-linux-mips
    - cd ../
    - tar -czf x-ui-linux-mips.tar.gz x-ui
    - mv x-ui-linux-mips.tar.gz /tmp/work/OUT/

    # arch: mips64
    - cd /tmp/work/mips/x-ui
    - mkdir -p bin
    - cp -r /tmp/ci/x-ui/src/x-ui.service ./
    - cp -r /tmp/ci/x-ui/src/x-ui.sh ./
    - cp -r /tmp/work/geoip/geoip.dat bin/
    - cp -r /tmp/work/geoip/geosite.dat bin/
    - mv /tmp/ci/x-ui/src/OUT/X-UI-linux-mips64 x-ui
    - mv /tmp/ci/Xray-Core/src/OUT/Xray-Core-linux-mips64 bin/xray-linux-mips64
    - cd ../
    - tar -czf x-ui-linux-mips64.tar.gz x-ui
    - mv x-ui-linux-mips64.tar.gz /tmp/work/OUT/

    # arch: mips64le
    # - cd /tmp/work/mips/x-ui
    # - mkdir -p bin
    # - cp -r /tmp/ci/x-ui/src/x-ui.service ./
    # - cp -r /tmp/ci/x-ui/src/x-ui.sh ./
    # - cp -r /tmp/work/geoip/geoip.dat bin/
    # - cp -r /tmp/work/geoip/geosite.dat bin/
    # - mv /tmp/ci/x-ui/src/OUT/X-UI-linux-mips64le x-ui
    # - mv /tmp/ci/Xray-Core/src/OUT/Xray-Core-linux-mips64le bin/xray-linux-mips64le
    # - cd ../
    # - tar -czf x-ui-linux-mips64le.tar.gz x-ui
    # - mv x-ui-linux-mips64le.tar.gz /tmp/work/OUT/

    # arch: mipsle
    # - cd /tmp/work/mips/x-ui
    # - mkdir -p bin
    # - cp -r /tmp/ci/x-ui/src/x-ui.service ./
    # - cp -r /tmp/ci/x-ui/src/x-ui.sh ./
    # - cp -r /tmp/work/geoip/geoip.dat bin/
    # - cp -r /tmp/work/geoip/geosite.dat bin/
    # - mv /tmp/ci/x-ui/src/OUT/X-UI-linux-mipsle x-ui
    # - mv /tmp/ci/Xray-Core/src/OUT/Xray-Core-linux-mipsle bin/xray-linux-mipsle
    # - cd ../
    # - tar -czf x-ui-linux-mipsle.tar.gz x-ui
    # - mv x-ui-linux-mipsle.tar.gz /tmp/work/OUT/

    # arch: riscv64
    - cd /tmp/work/mips/x-ui
    - mkdir -p bin
    - cp -r /tmp/ci/x-ui/src/x-ui.service ./
    - cp -r /tmp/ci/x-ui/src/x-ui.sh ./
    - cp -r /tmp/work/geoip/geoip.dat bin/
    - cp -r /tmp/work/geoip/geosite.dat bin/
    - mv /tmp/ci/x-ui/src/OUT/X-UI-linux-riscv64 x-ui
    - mv /tmp/ci/Xray-Core/src/OUT/Xray-Core-linux-riscv64 bin/xray-linux-riscv64
    - cd ../
    - tar -czf x-ui-linux-riscv64.tar.gz x-ui
    - mv x-ui-linux-riscv64.tar.gz /tmp/work/OUT/

    # arch: s390x
    - cd /tmp/work/mips/x-ui
    - mkdir -p bin
    - cp -r /tmp/ci/x-ui/src/x-ui.service ./
    - cp -r /tmp/ci/x-ui/src/x-ui.sh ./
    - cp -r /tmp/work/geoip/geoip.dat bin/
    - cp -r /tmp/work/geoip/geosite.dat bin/
    - mv /tmp/ci/x-ui/src/OUT/X-UI-linux-s390x x-ui
    - mv /tmp/ci/Xray-Core/src/OUT/Xray-Core-linux-s390x bin/xray-linux-s390x
    - cd ../
    - tar -czf x-ui-linux-s390x.tar.gz x-ui
    - mv x-ui-linux-s390x.tar.gz /tmp/work/OUT/

  release_script:
    - cd /tmp/ci/x-ui/src
    - gh config set git_protocol ssh --host github.com
    - touch mytoken.txt
    - echo "$TOKEN" > mytoken.txt
    - gh auth login --with-token < mytoken.txt
    - bash <(curl -Ls https://raw.githubusercontent.com/dopaemon/x-ui/main/release.sh)
    - echo "yes" | gh release create $VERSIONS /tmp/work/OUT/*.tar.gz --notes "$INFORELEASE" --title "X-UI $VERSIONS - Weekly - $(date +"%d-%m-%Y")"
